<?php
$escape = $this->plugin('escapeHtml');
$fragment = 'item-linked';
if ('Omeka\Api\Representation\ItemSetRepresentation' === get_class($objectResource)) {
    $fragment = 'item-set-linked';
}
$pagination = $this->pagination(null, $totalCount, $page, $perPage);
$pagination->setFragment($fragment);
?>
<div id="linked-resources">
<?php foreach ($subjectValues as $term => $values): ?>
<ul class="resource-list">
    <?php foreach ($values as $value): ?>
    <?php
    $template = $value->resource()->resourceTemplate();
    $templateProperty = $template ? $template->resourceTemplateProperty($value->property()->Id()) : null;
    $altLabel = $templateProperty ? $templateProperty->alternateLabel() : null;
    ?>
    <li class="item resource">
        <?php if ($volumeNumber = $value->resource()->value('schema:volumeNumber')): ?>
        <div class="volumeNumber"><?php echo 'Vol. n° ' ?><?php echo $volumeNumber; ?></div>
        <?php endif; ?>
        <center><?php echo $value->resource()->linkRaw($this->thumbnail($value->resource(), 'medium')); ?></center>
        <p class="customType"><b><?php echo $value->resource()->value('dcterms:type'); ?></b></p>
        <div class='browseTitre'><center><h4><?php echo $value->resource()->linkRaw($value->resource()->value('dcterms:title')); ?></h4></center></div>
        <?php if ($description = $value->resource()->value('dcterms:description')): ?>
        <div class="description"><?php echo mb_substr($description,0,75); echo $value->resource()->linkRaw('...'); ?></div></br>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php endforeach; ?>

<?php echo ($totalCount > $perPage) ? '<div class="linked-footer">' . $pagination . '</div>' : ''; ?>

</div>

<script>
$('#filter-property').on('change', function(e) {
    var thisSelect = $(this);
    var property = thisSelect.find(':selected').val();
    var url = thisSelect.data('url');
    var fragment = thisSelect.data('fragment');
    window.location = url + '?' + $.param({property: property}) + '#' + fragment;
});
</script>
