<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');

$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();

$sortHeadings = [
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
    [
        'label' => $translate('Type'),
        'value' => 'dcterms:type'
    ],
];

?>
<?php if (isset($itemSet)): ?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id(); ?>
<?php endif; ?>
<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <center><?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?></center>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>
<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <li class="item resource">
<!-- set inventarisnummer in image -->
<?php if ($invnr = $item->value('modsrdf:identifier')): ?>
  <div class="volumeNumber"><!--<?php echo 'invnr ' ?>--><?php echo $invnr; ?></div>
<?php endif; ?>
        <?php if ($thumbnail = $this->thumbnail($item, 'medium')): ?>
<!--linkraw, moet over hele cel -->
        <?php echo '<center>'; echo $item->linkRaw($thumbnail); echo '</center>';?>
        <?php endif; ?>
<!--        <p class="customType"><b><?php echo $item->value('dcterms:subject'); ?></b></p> -->
        <div class='browseTitre'><center><h3><?php echo $item->link($item->value('dcterms:subject')); ?></h3></center></div>
        <?php if ($description = $item->value('dcterms:description')): ?>
<!--        <div class="browseTitre"><center><h4><?php echo $item->link(mb_substr($item->value('dcterms:subject'),0,75)); ?></h4></center></div></br> -->
        <div class="description"><?php echo mb_substr($description,0,75); echo $item->link('...'); ?></div></br>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php echo $this->pagination(); ?>
<?php // $this->trigger('view.browse.after'); ?>
