<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
$this->htmlElement('body')->appendAttribute('class', 'index search');
?>

<?php echo $this->pageTitle(sprintf($this->translate('Search results for “%s”'), $query)); ?>

<div>
    <h2><?php echo 'Items' ; ?></h2>
    <?php if ($items): ?>

    <?php echo $this->hyperlink(
        sprintf($this->translate('View all results'), $itemsTotal),
        $this->url(
            'site/resource',
            ['controller' => 'item', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $query]],
            true
        )
    ); ?>
<!-- start totalresults -->
<?php
  echo '(total)', $totalCount;
?>
<!-- end totalresults -->

<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <li class="item resource">
<!-- set inventarisnummer in image -->
      <?php if ($invnr = $item->value('modsrdf:identifier')): ?>
        <div class="volumeNumber"><!--<?php echo 'invnr ' ?>--><?php echo $invnr; ?></div>
      <?php endif; ?>
        <?php if ($thumbnail = $this->thumbnail($item, 'medium')): ?>
        <?php echo '<center>'; echo $item->linkRaw($thumbnail); echo '</center>';?>
        <?php endif; ?>
        <div class='browseTitre'><center><h3><?php echo $item->link($item->value('dcterms:subject')); ?></h3></center></div>
        <?php if ($description = $item->value('dcterms:description')): ?>
        <div class="description"><?php echo mb_substr($description,0,75); echo $item->link('...'); ?></div></br>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
    <?php echo $this->hyperlink(
        sprintf($this->translate('View all results'), $itemsTotal),
        $this->url(
            'site/resource',
            ['controller' => 'item', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $query]],
            true
        )
    ); ?>

    <?php else: ?>
    <p><?php echo $this->translate('No results'); ?></p>
    <?php endif; ?>
</div>
<!-- Keep this and adapt if you want to show other result (e.g. materials, agents, documents books,...)
<div>
    <h2><?php echo 'Articles' ; ?></h2>
    <?php if ($pages): ?>
    <ul class="searchPages">
        <?php foreach ($pages as $page): ?>
        <li class="listPages"><h4><?php echo $page->link($page->title()); ?></h4></li>
        <?php endforeach; ?>
    </ul>
    <?php else: ?>
    <p><?php echo $this->translate('No results'); ?></p>
    <?php endif; ?>
</div>
-->
